### ISSUE TITLE
Mistakes in docker-compose file

### ISSUE THREAD

**Issue by nithin-bose** [rakam-io/rakam#35]

**Comment by buremba** [comment]
I renamed db service to rakam-db. Is it fine now?

**Comment by nithin-bose** [comment]
yup. In the README extract of the compose file. I think it should be ``image: buremba/rakam``. I was about to give you a PR :)

**Comment by buremba** [comment]
Ah, thanks. :) Feel free to open a PR for `image` tag.

**Comment by buremba** [comment]
fixed with #36
