### ISSUE TITLE
Event explorer does not load

### ISSUE THREAD

**Issue by fignuts** [rakam-io/rakam#48]
```ERROR: column "_time" does not exist Position: 40```

There is no error or stack trace in the server logs. Using postgresql deployment type with latest git version from 3/4.

**Comment by buremba** [comment]
Normally, `_time` attribute is attached the all collections when they're created. Did you manually create the tables?

**Comment by fignuts** [comment]
No, I have not manually created any tables or made any changes to the _time attribute.

I checked my schema and every table has a _time column except for _users.

**Comment by buremba** [comment]
I see, thanks for the explanation. I finally reproduced the bug and pushed a fix to master branch.

**Comment by fignuts** [comment]
Thanks for the quick fixes on the issues! I appreciate it.
