### ISSUE TITLE
Add druid backend

### ISSUE THREAD

**Issue by kerwin** [rakam-io/rakam#52]
Druid is on other option for analytics-oriented backend. Any plato to support Druid?

**Comment by buremba** [comment]
That's in our roadmap but I'm waiting Druid to support SQL officially.

**Comment by kerwin** [comment]
Is there any document for how to deploy rakam with presto backend?

**Comment by buremba** [comment]
Here is the PrestoDB module configuration: http://rakam.io/config#org.rakam.presto.PrestoModule
Note that if you want to be able collec data in real-time, you also need to use AWS Kinesis or Kafka in front of PrestoDB. Here is an example config: https://gist.github.com/buremba/adcc8ac34e56642b2fd5539abae5f9dd

If you can send a message to us from this page https://rakam.io/contact we can send you the Cloudformation template that allows you to install the full infrastructure on AWS.

**Comment by kerwin** [comment]
Thanks
