### ISSUE TITLE
Heroku deploy button results in an error page

### ISSUE THREAD

**Issue by davidmann4** [rakam-io/rakam#53]
After I deployed rakam via your heroku button I get this screen:
![image](https://cloud.githubusercontent.com/assets/1736570/24332254/cbdf8b1c-1243-11e7-8238-c612416d0212.png)

logs:
![image](https://cloud.githubusercontent.com/assets/1736570/24332266/dbc5bc72-1243-11e7-983a-cbf455d5cf8b.png)

**Comment by davidmann4** [comment]
without geoip it worked

**Comment by buremba** [comment]
Fixed in 616400c84445b75d859f72c224222d64bb9d974f. Thanks for reporting the bug!
