### ISSUE TITLE
User Explorer does not work

### ISSUE THREAD

**Issue by davidmann4** [rakam-io/rakam#56]
Hi, 

jsut a reminder on my issue with your "peoples" feature in rakam. Did you already solved it?

cheers,

David

**Comment by buremba** [comment]
Hey David,

Thanks for creating the issue. It looks like `id` property is reserved and ignored in API. 
You may either change the call `new rakam.User().set({'id': userID})` to something like `new rakam.User().set({'user_id': userID})` as a workaround or upgrade the latest version of API.

**Comment by davidmann4** [comment]
solution was to call this methods inside the rakam.init callback
