### ISSUE TITLE
Multiple funnel by choice of configuration instead of only user.  

### ISSUE THREAD

**Issue by sambitdixit** [rakam-io/rakam#59]
Have a "funnel by" dropdown where we can configure predefined columns like user, session, demandid etc on which group by can be applied to funnel query. Also these should not appear again as part of global group by shown at bottom part where funnel graph is getting displayed so that people should not do multiple group by on same column. Basically exclude those "funnel by" fields from group by dropdown in funnel graph UI.

**Comment by buremba** [comment]
We use the term `connector field` and the default is the `_user` field when you select the steps. When the user opens up the advanced section, she will see the `connector field` option and be able to select custom fields.
