### ISSUE TITLE
Explorer Page Performance and Control 

### ISSUE THREAD

**Issue by sambitdixit** [rakam-io/rakam#60]
We need to have incremental materialization in explorer UI. As soon as a user enters Explorer page, it shows lot of stats about all collections. These data keep changing as data load happens. These should be pre incrementally materialised so that these stats should not be fetched from Presto backend raw data every time. 

The collections panel on left side of Explorer UI should show top 10 collections by count. If i have 500 collections, we can not show all of them. 

On the right hand side UI, we should provide limit on no of collections people can chose to see at a time for example 10/20 collections at a time. This should be configurable. This is to restrict large bad queries hitting presto e.g people chose all collections or when you enter the Explorer UI it fetches data for all collections (fetching data for all 500 collections on every page visit is going to unnecessarily load Presto).

**Comment by buremba** [comment]
Now we use incremental materialized views in event explorer. Right now, we didn't restrict the count of selected collections and can discuss and testthe performance of it. If it really affects the performance, then we may put some restrictions as you explained.

**Comment by buremba** [comment]
Fixed in master.
