### ISSUE TITLE
Custom Connector Field in Advanced Setting of Funnel Page

### ISSUE THREAD

**Issue by sambitdixit** [rakam-io/rakam#61]
When i select the check box for Custom Connector field, the text box is not editable immediately unless i uncheck and check it back again. Then it shows the list of columns for a collection and when i use mouse to scroll down and select, it does not work, instead if i use arrow down button in keyboard and press enter at selected value, it works. This is happening in Safari browser Version 10.1 (12603.1.30.0.34).

**Comment by buremba** [comment]
It should be working fine right now. Could you please check it again?
P.S: The issue normally belongs to https://github.com/rakam-io/rakam-ui/issues

**Comment by sambitdixit** [comment]
ok have you put a new fix and i need to make a new deployment ?

**Comment by buremba** [comment]
yes, could you please make a new deployment?
