### ISSUE TITLE
Rakam Presto Raptor Drop Tables

### ISSUE THREAD

**Issue by sambitdixit** [rakam-io/rakam#63]
When we ingest data to Presto as a new event collection and try to drop the table, it does not delete actual storage, we need to understand if there are some settings we need to use for this.

**Comment by buremba** [comment]
We do not allow users to delete data from Rakam via an API because of security reasons. However; when you execute DELETE FROM or DROP TABLE on presto-cli, Presto schedules the shards to be deleted in an hour, it doesn’t remove the data immediately in order to avoid concurrency issues.
