### ISSUE TITLE
Show saved funnel and retention results when user comes back 

### ISSUE THREAD

**Issue by sambitdixit** [rakam-io/rakam#67]
1. If an user has saved a predefined date range specific funnel and named it as funnel_dt1, then he comes back tomorrow and wants to see his old saved funnel "funnel_dt1", it shows blank results since the funnel is saved with only name but not with results, all filter criteria, date etc. This is required since many analysts want to compare the funnels they created earlier and new funnels to compare how it behaves. The same approach is required for retention as well. Basically what users mean by save means, the output is saved and then when they come back they can check the old values, at the time the filters, date range in calendar should be repopulated to old values selected in old saved funnel query. 

2. In the saved funnel list section, the Search box says "Search in reports" and when i type anything it should show me list of saved funnels. Lets say users have created 100 + funnels, then they want to search funnels by typing initial 2 letters in the search box. Why should they search reports in funnel section. If some one has created a custom funnel by writing own SQL and saved as a Funnel in Reports section, then that should automatically show up in Funnel section and show when Search in funnels section.

**Comment by buremba** [comment]
1. The data-range is not saved as part of funnel. They are dynamic and changing over time. The only use case of this feature is that when an analysts visits the funnel in a specific day and come back later, we can show the old values. This has an issue because the result will not be real-time and we need to write somewhere in the page that the results that are shown are not actually real-time and populated from cache.

2. The searchbox feature actually searchs for funnel reports. We use the term "Search in reports" in all reports, funnel and retention pages. I will change it to "Search in funnels" in order to avoid confusion.

**Comment by sambitdixit** [comment]
For the point 1, the use case is 
As an analysts, today i prepared a funnel by selecting some collections, fields, group by columns and date range. Then i saved it. Now my product manager comes back and asks to prepare another funnel with a different date and then he asked me to share the funnels to him so that he can watch those two funnels in his dashboard and compare. 

Now few days later my product manager comes back and asked me to change one parameter for one of the funnel and asked refresh the funnel for a new date and save it back.

**Comment by buremba** [comment]
1. We actually have caching feature in dashboard. When we add support for funnel and retention in dashboard, I believe that we can cover this use-case. We already has a pending issue for dashboard support and will prioritize it for you: https://github.com/rakam-io/rakam-ui/issues/30

2. The current functionality actually is exactly what you asked for. However the naming was confusing and I renamed that placeholder.

**Comment by sambitdixit** [comment]
Hi Buremba,
   Any idea when ask 1 you are planning to get started. 

  On point 2, i could not find a funnel by name in search box if i have 50 funnels saved. 

Regards
-Sambit

**Comment by buremba** [comment]
1. Feature is implemented.
2. There was a bug in search search, could you please check it again?

**Comment by sambitdixit** [comment]
For point 1, even if we add to dashboard people dont see what conditions and filters were used to build the funnel and it will be better if we follow following in Funnel page to make it more clean. 
1. Query - Build steps of funnel, add filters and groupBy and then query - Objective is to explore ad hoc funnel creation. 
2. Save - Once ad hoc exploration looks fine, people wants to save the funnel and define cache strategy so that when they come back tomorrow they can see the saved data and all selected steps, filters, groupBy will show pre populated as what it was when saved. Then they can pin to dashboard and it can there show in the dashboard. 
3. Edit - People want to come back tomorrow and change the steps or filter and reserve it. This time they should be able to save against the same name or a different name. It should popup a window to ask Do you want to replace existing one or save as a new one, ask for to cache or not etc. 
4. Delete - People want to delete the funnel later once they see its no more required.

**Comment by buremba** [comment]
The issue here is that you don't want to use dashboards and instead have caching feature available in funnel page, right? Is there anything that I'm missing?

**Comment by sambitdixit** [comment]
Everytime a user comes back, he wants to see funnel he created earlier and saved and now he wants to compare old one with a new date range or filter based funnel which he created today. How do we achieve this in current setup.
