### ISSUE TITLE
Funnel Filter Operator IN does not work as expected 

### ISSUE THREAD

**Issue by sambitdixit** [rakam-io/rakam#78]
When i add filter, lets say i chose dimension as "platform" from filter and then chose operator as "in", then i entered following in the textbox  "android,iphone,windows
<img width="1333" alt="screen shot 2017-08-21 at 5 54 25 pm" src="https://user-images.githubusercontent.com/1338801/29519125-d5f63a2c-8699-11e7-8e45-2f14063f37bc.png">
".

**Comment by buremba** [comment]
The problem was that the comma doesn't actually add new items to the list. You need to press `enter` in order to add new items. Also pressing the apply button doesn't help since it doesn't have control on the input element.
I added a placeholder that says `press enter to add`, hope it helps.

**Comment by sambitdixit** [comment]
thanks it works
