### ISSUE TITLE
Project name cannot start with numbers and cannot contain special chars

### ISSUE THREAD

**Issue by rafaelamorim** [rakam-io/rakam#86]
Hello guys, how's going?

Thanks for the awesome support last time! 🥇 

I officially started using Rakam for my project and somehow i stumble upon this issue...

If i create a project name starting with numbers or containing special chars, `Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "[project name]"...` errors will popup whenever trying to create/update a user or event.

This seems to happen because project's name are not being escaped with quotes when querying the DB. I.E.: `SELECT * FROM 59e039814c39f503aadf0b6a._users LIMIT 1` fails, but: `SELECT * FROM "59e039814c39f503aadf0b6a"._users LIMIT 1` works :)

Best regards

**Comment by buremba** [comment]
Hey @rafaelamorim, I applied fix for a possible bug. Where do you see this error, in people section?

**Comment by rafaelamorim** [comment]
@buremba people and events too...

**Comment by buremba** [comment]
OK, it should be fixed now. Could you please check it for me?

**Comment by rafaelamorim** [comment]
@buremba, sorry for taking too long to respond.

everything is working 100% flawlessly now! 🥇 

thanks! 👍
