### ISSUE TITLE
Not able to completely see suggestions in event explorer

### ISSUE THREAD

**Issue by kkarthikpsgtech** [rakam-io/rakam#91]
When suggested text is bigger, it trims characters at last and appends with "..."
<img width="419" alt="screen shot 2017-11-24 at 3 44 25 pm" src="https://user-images.githubusercontent.com/13032361/33205877-7b7641ca-d12e-11e7-8aa9-3495af004fc9.png">

**Comment by rajivonat** [comment]
@buremba @kazim-i We need a fix for this by weekend. Please let us know if any questions

**Comment by buremba** [comment]
Now the default 350px and the three dots are only visible when there is no space. I also added title to the element so if you hover it you will see the full collection name. Please try and let me know what you think. We can also make all dropdowns scrollable in x axis.

<img width="510" alt="screen shot 2017-11-24 at 5 22 02 am" src="https://user-images.githubusercontent.com/82745/33212367-8c3e22a4-d0d7-11e7-80e2-332fb1a95bc7.png">

**Comment by saloni2409** [comment]
Its better if its scrolable on x-axis.

**Comment by buremba** [comment]
Done
